fos_rest:
  body_listener:
    enabled: true
  format_listener:
    rules:
      - { path: '^/', priorities: [ 'json' ], fallback_format: ~, prefer_extension: false }
  view:
    view_response_listener: 'force'
    formats:
      json: true